/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cuminhtien;
@org.apache.avro.specific.AvroGenerated
public enum gender implements org.apache.avro.generic.GenericEnumSymbol<gender> {
  FEMALE, MALE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"gender\",\"namespace\":\"com.cuminhtien\",\"symbols\":[\"FEMALE\",\"MALE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
